fix: respect {} in safe typestring splitting
electron/docs-parser pull request #46
Opened 2020-10-23 20:14 UTC by nornagon

This allows constructions such as:

```md
### `foo(bar)`

* `bar` Function<{type: 'a'} | { type: 'b', extraThing? 'c' }>
```

2020-10-24 00:59 UTC, ckerr approved these changes

2020-10-24 04:22 UTC, MarshallOfSound requested changes
Can you add a test for what this is supposed to support, I'm not sure how this achieves what you put in the PR body

2020-10-26 17:36 UTC, nornagon commented
@MarshallOfSound test added. This PR makes commas inside of a `{}` pair part of the type itself, instead of splitting when it encounters a `,` inside `{}`.

Before, `Function<{foo: A, bar: B}>` would parse as a function type with two arguments, of type `{foo: A` and `bar: B}`. Now, it parses as a function type with one argument, of type `{foo: A, bar: B}`.

2020-10-26 19:03 UTC, MarshallOfSound approved these changes

2020-10-26 19:03 UTC, merged